name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compute next tag
        id: compute_tag
        uses: craig-day/compute-tag@v15
        with:
          branch: main
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: path
      - name: Package
        env:
          TAG: ${{steps.compute-tag.outputs.next_tag}}
        run: zip -r drones-${TAG}.zip drones
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: ${{ steps.compute_tag.outputs.next_tag }}
          tag_name: ${{ steps.compute_tag.outputs.next_tag }}
          generate_release_notes: true
          files: |
            drones-${{steps.compute-tag.outputs.next_tag}}.zip

